Hotel_mvc1/Controllers/RezervacijeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_mvc1.Models;
using System.Data.SqlClient;
using System.Windows;

namespace Hotel_mvc1.Controllers
{
   
    public class RezervacijeController : Controller
    {
        private hotelBazaContext db = new hotelBazaContext();

        // GET: Rezervacije
        public ActionResult Index()
        {
            
            Session["MaxIDSoba"]= db.soba.Count();
            return View(db.rezervacija.ToList());
        }

        // GET: Rezervacije/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }
        public ActionResult Slobodni()
        {
            return View();
        }
        public ActionResult SlobodneSobe()
        {
            return View();
        }

        public ActionResult JeRezervirano(int idSoba, DateTime rezervacijaOd, DateTime rezervacijaDo)
        {
            string obavijest = "<p style='color: green;'><strong>Rezervacija slobodna.</strong></p>";
            List<Rezervacija> rezervacije = db.rezervacija.ToList();
            List<Soba> sobe = db.soba.ToList();
            Soba so = sobe.Find(x => x.idsoba == idSoba);
            int id = so.idsoba;

            foreach (Rezervacija rez in rezervacije)
            {
                //  
                if (rez.id_soba == id)
                {
                    if ((rez.rezerviranoDo < rezervacijaOd && rez.rezerviranoDo < rezervacijaDo) ||
                        (rez.rezerviranoOd > rezervacijaDo && rez.rezerviranoOd > rezervacijaOd))
                    {
                        continue;
                    }
                    else
                    {
                        obavijest = "<p style='color: red;'><strong>Rezervacija već postoji!</strong></p>";
                        break;
                    }
                }
                continue;
            }

            if (obavijest.Contains("slobodna"))
            {
                TimeSpan rasponRezervacije = (rezervacijaDo - rezervacijaOd);
                double brojdana = rasponRezervacije.TotalDays;
                

                Soba s = sobe.Find(x => x.idsoba == idSoba);

                if (s != null)
                {
                    double cijena = brojdana * s.cijenaSobe;

                    obavijest += "<br><p style='color: green;'>Cijena rezervacije: " + cijena.ToString() + " kn</p>";
                }
                else
                {
                    obavijest = "<br><p style='color: red'>Soba pod odabranim brojem ne postoji!</p>";
                }
            }

            return Json(obavijest, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Slobodni([Bind(Include = "rezerviranoOd,rezerviranoDo")] Rezervacija rezervacija)
        {

            Session["rezOd"] = rezervacija.rezerviranoOd.ToString();
            Session["rezDo"] = rezervacija.rezerviranoDo.ToString();

            List<Rezervacija> rezervacije = new List<Rezervacija>();
            List<Soba> sl_sobe = new List<Soba>();
            sl_sobe = db.soba.ToList();
            rezervacije = db.rezervacija.ToList();
            foreach(Rezervacija a in rezervacije)
            {
               
                if ((rezervacija.rezerviranoOd < a.rezerviranoOd && rezervacija.rezerviranoDo < a.rezerviranoOd) ||
                    (rezervacija.rezerviranoOd > a.rezerviranoDo && rezervacija.rezerviranoDo > a.rezerviranoDo))   //&& rezervacija.rezerviranoDo < a.rezerviranoOd?
                {
                      
                }
                else
                {    banana:
                    foreach(Soba b in sl_sobe)
                    {
                        if (b.idsoba == a.id_soba)
                        {
                            sl_sobe.RemoveAt(sl_sobe.IndexOf(b));
                            goto banana; 
                        }
                    }
                //sl_sobe.RemoveAt(a.id_soba);
                //sl_sobe.IndexOf(); 
                    
                }  
            }
            return View("SlobodneSobe",sl_sobe);
        }

           
        
        // GET: Rezervacije/Create
        public ActionResult Create(int? id)
        {
            if (id != null)
            {
                Session["sobaID"] = id;
                return View();
            }
            else
            return View();
        }

        // POST: Rezervacije/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idrezervacija,id_korisnik,id_soba,rezerviranoOd,rezerviranoDo")] Rezervacija rezervacija)
        {
           DateTime d1= rezervacija.rezerviranoOd;
            DateTime d2=rezervacija.rezerviranoDo;
            
            TimeSpan d3 =(d2 - d1);
            double brojdana = d3.TotalDays;
            List<Soba> sobe = new List<Soba>();
            sobe = db.soba.ToList();
            Soba s = sobe.Find(x => x.idsoba == rezervacija.id_soba);
            double cijena = brojdana * s.cijenaSobe;
            rezervacija.cijena = cijena.ToString()+" kn";
            rezervacija.datumRezervacije = DateTime.Now;
            rezervacija.id_korisnik = Convert.ToInt32(Session["idkorisnik"]);
          //  
            List<Rezervacija> rezervacije = new List<Rezervacija>();
         //   List<DateTime> datumi = new List<DateTime>();
            rezervacije = db.rezervacija.ToList();
           // 
           // 
          //  rezervacija.cijena=a.cijenaSobe * Convert.ToInt32(vrijemeNocenja);
            bool vecRez = false;
            int check = 0;

            if (rezervacija.rezerviranoOd > rezervacija.rezerviranoDo)
                return View(rezervacija);
            if (rezervacija.rezerviranoOd < DateTime.Now || rezervacija.rezerviranoOd < DateTime.Now)
                return View(rezervacija);

            if (ModelState.IsValid)
            {
                //  var rezervirano = db.rezervacija.Where(r => r.id_soba == rezervacija.id_soba);//.Where(r => r.rezerviranoOd > rezervacija.rezerviranoDo)||.Where(r => r.rezerviranoDo < rezervacija.rezerviranoOd);


                foreach (Rezervacija a in rezervacije)
                {

                    if (rezervacija.id_soba == a.id_soba)
                    {
                            if ((rezervacija.rezerviranoOd < a.rezerviranoOd && rezervacija.rezerviranoDo < a.rezerviranoOd) ||
                                (rezervacija.rezerviranoOd > a.rezerviranoDo && rezervacija.rezerviranoDo > a.rezerviranoDo ))//&& rezervacija.rezerviranoDo < a.rezerviranoOd?
                        {
                                check++;
                            }
                            else
                            {
                                vecRez = true;
                                break;
                            }
                        }
                    }
                    if (vecRez == true)
                    {
                        return View(rezervacija);
                    }
                    else {
                        db.rezervacija.Add(rezervacija);
                        db.SaveChanges();
                    Session["sobaID"] = null;
                //??
                        return RedirectToAction("Index");
                    }
               // return View(rezervacija);
            }
            return View(rezervacija);
        }

        // GET: Rezervacije/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // POST: Rezervacije/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idrezervacija,id_korisnik,id_soba,cijena,datumRezervacije,rezerviranoOd,rezerviranoDo")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rezervacija).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rezervacija);
        }

        // GET: Rezervacije/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // POST: Rezervacije/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervacija rezervacija = db.rezervacija.Find(id);
            db.rezervacija.Remove(rezervacija);
            db.SaveChanges();

Hotel_mvc1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        tr:nth-of-type(even) {
            background-color: #ccc;
        }
    </style>
    @*<link rel="stylesheet" href="blueberry.css" />
    <style type="text/css">
        {
            margin: 0;
            border: 0;
            padding: 0;
        }

        body {
            background-image: url('../Slike/Doors.png');
            
            background-size: cover;
            font: 14px/20px Arial,San-Serif;
            color: #555;
            margin: 0;
        }

        h1 {
            text-align: center;
            font-size: 180%;
            line-height: 120%;
            padding: 5% 0;
        }

        h2 {
            text-decoration: underline;
            line-height: 280%;
            padding-left: 2%;
        }

        h3 {
            line-height: 110px;
            padding: 5% 0;
        }

        p {
            padding: 1%;
        }

        img {
            text-align: center;
            max-width: 100%;
            height: auto;
            width: auto;
        }

        a {
            color: #FFF;
            text-decoration: none;
            font-weight: bold;
        }

            a:hover {
                color: #FFF;
                text-decoration: underline;
            }

        ul {
            list-style: none;
        }

        header {
            background: #405580;
            width: 100%;
            height: 86px;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 100;
            opacity: 0.90;
        }

       

        nav {
            float: right;
            padding: 35px 20px 20px 0px;
        }


        a:hover#menu-icon {
            border-radius: 4px 4px 0 0;
        }

        nav ul li {
            display: inline-block;
            float: left;
            padding: 10px;
        }
    </style>
    <script src="https://ajax.googleapi.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
    <script src="jquery.blueberry.js"></script>

    <script>
        $(window).load(function(){
            $('.blueberry').blueberry();
        });
    </script>*@

</head>
@{string session = (string)Session["uloga"];

}

<body class="body-content">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel booking", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Sobe", "Index", "Sobe")</></li>
                        @if (Session["idkorisnik"] != null)
                        {
                    <li>@Html.ActionLink("Moje Rezervacije", "Index", "Rezervacije")</li>
                        }
                        @if (session == "admin")
                        {
                    <li>@Html.ActionLink("Korisnici", "Index", "Korisnici")</li>
                        }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hotel booking</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>