Hotel_mvc1/Controllers/RezervacijeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_mvc1.Models;
using System.Data.SqlClient;
using System.Windows;

namespace Hotel_mvc1.Controllers
{
   
    public class RezervacijeController : Controller
    {
        private hotelBazaContext db = new hotelBazaContext();

        // GET: Rezervacije
        public ActionResult Index()
        {
            
            Session["MaxIDSoba"]= db.soba.Count();
            return View(db.rezervacija.ToList());
        }

        // GET: Rezervacije/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }
        public ActionResult Slobodni()
        {
            return View();
        }
        public ActionResult SlobodneSobe()
        {
            return View();
        }

        public ActionResult JeRezervirano(int idSoba, DateTime rezervacijaOd, DateTime rezervacijaDo)
        {
            string obavijest = "<p style='color: green;'><strong>Rezervacija slobodna.</strong></p>";
            List<Rezervacija> rezervacije = db.rezervacija.ToList();
            List<Soba> sobe = db.soba.ToList();
            Soba so = sobe.Find(x => x.idsoba == idSoba);
            int id = so.idsoba;

            foreach (Rezervacija rez in rezervacije)
            {
                //  
                if (rez.id_soba == id)
                {
                    if ((rez.rezerviranoDo < rezervacijaOd && rez.rezerviranoDo < rezervacijaDo) ||
                        (rez.rezerviranoOd > rezervacijaDo && rez.rezerviranoOd > rezervacijaOd))
                    {
                        continue;
                    }
                    else
                    {
                        obavijest = "<p style='color: red;'><strong>Rezervacija već postoji!</strong></p>";
                        break;
                    }
                }
                continue;
            }

            if (obavijest.Contains("slobodna"))
            {
                TimeSpan rasponRezervacije = (rezervacijaDo - rezervacijaOd);
                double brojdana = rasponRezervacije.TotalDays;
                

                Soba s = sobe.Find(x => x.idsoba == idSoba);

                if (s != null)
                {
                    double cijena = brojdana * s.cijenaSobe;

                    obavijest += "<br><p style='color: green;'>Cijena rezervacije: " + cijena.ToString() + " kn</p>";
                }
                else
                {
                    obavijest = "<br><p style='color: red'>Soba pod odabranim brojem ne postoji!</p>";
                }
            }

            return Json(obavijest, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Slobodni([Bind(Include = "rezerviranoOd,rezerviranoDo")] Rezervacija rezervacija)
        {

            Session["rezOd"] = rezervacija.rezerviranoOd.ToString();
            Session["rezDo"] = rezervacija.rezerviranoDo.ToString();

            List<Rezervacija> rezervacije = new List<Rezervacija>();
            List<Soba> sl_sobe = new List<Soba>();
            sl_sobe = db.soba.ToList();
            rezervacije = db.rezervacija.ToList();
            foreach(Rezervacija a in rezervacije)
            {
               
                if ((rezervacija.rezerviranoOd < a.rezerviranoOd && rezervacija.rezerviranoDo < a.rezerviranoOd) ||
                    (rezervacija.rezerviranoOd > a.rezerviranoDo && rezervacija.rezerviranoDo > a.rezerviranoDo))   //&& rezervacija.rezerviranoDo < a.rezerviranoOd?
                {
                      
                }
                else
                {    banana:
                    foreach(Soba b in sl_sobe)
                    {
                        if (b.idsoba == a.id_soba)
                        {
                            sl_sobe.RemoveAt(sl_sobe.IndexOf(b));
                            goto banana; 
                        }
                    }
                //sl_sobe.RemoveAt(a.id_soba);
                //sl_sobe.IndexOf(); 
                    
                }  
            }
            return View("SlobodneSobe",sl_sobe);
        }

           
        
        // GET: Rezervacije/Create
        public ActionResult Create(int? id)
        {
            if (id != null)
            {
                Session["sobaID"] = id;
                return View();
            }
            else
            return View();
        }

        // POST: Rezervacije/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idrezervacija,id_korisnik,id_soba,rezerviranoOd,rezerviranoDo")] Rezervacija rezervacija)
        {
           DateTime d1= rezervacija.rezerviranoOd;
            DateTime d2=rezervacija.rezerviranoDo;
            
            TimeSpan d3 =(d2 - d1);
            double brojdana = d3.TotalDays;
            List<Soba> sobe = new List<Soba>();
            sobe = db.soba.ToList();
            Soba s = sobe.Find(x => x.idsoba == rezervacija.id_soba);
            double cijena = brojdana * s.cijenaSobe;
            rezervacija.cijena = cijena.ToString()+" kn";
            rezervacija.datumRezervacije = DateTime.Now;
            rezervacija.id_korisnik = Convert.ToInt32(Session["idkorisnik"]);
          //  
            List<Rezervacija> rezervacije = new List<Rezervacija>();
         //   List<DateTime> datumi = new List<DateTime>();
            rezervacije = db.rezervacija.ToList();
           // 
           // 
          //  rezervacija.cijena=a.cijenaSobe * Convert.ToInt32(vrijemeNocenja);
            bool vecRez = false;
            int check = 0;

            if (rezervacija.rezerviranoOd > rezervacija.rezerviranoDo)
                return View(rezervacija);
            if (rezervacija.rezerviranoOd < DateTime.Now || rezervacija.rezerviranoOd < DateTime.Now)
                return View(rezervacija);

            if (ModelState.IsValid)
            {
                //  var rezervirano = db.rezervacija.Where(r => r.id_soba == rezervacija.id_soba);//.Where(r => r.rezerviranoOd > rezervacija.rezerviranoDo)||.Where(r => r.rezerviranoDo < rezervacija.rezerviranoOd);


                foreach (Rezervacija a in rezervacije)
                {

                    if (rezervacija.id_soba == a.id_soba)
                    {
                            if ((rezervacija.rezerviranoOd < a.rezerviranoOd && rezervacija.rezerviranoDo < a.rezerviranoOd) ||
                                (rezervacija.rezerviranoOd > a.rezerviranoDo && rezervacija.rezerviranoDo > a.rezerviranoDo ))//&& rezervacija.rezerviranoDo < a.rezerviranoOd?
                        {
                                check++;
                            }
                            else
                            {
                                vecRez = true;
                                break;
                            }
                        }
                    }
                    if (vecRez == true)
                    {
                        return View(rezervacija);
                    }
                    else {
                        db.rezervacija.Add(rezervacija);
                        db.SaveChanges();
                    Session["sobaID"] = null;
                //??
                        return RedirectToAction("Index");
                    }
               // return View(rezervacija);
            }
            return View(rezervacija);
        }

        // GET: Rezervacije/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // POST: Rezervacije/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idrezervacija,id_korisnik,id_soba,cijena,datumRezervacije,rezerviranoOd,rezerviranoDo")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rezervacija).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rezervacija);
        }

        // GET: Rezervacije/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // POST: Rezervacije/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervacija rezervacija = db.rezervacija.Find(id);
            db.rezervacija.Remove(rezervacija);
            db.SaveChanges();

Hotel_mvc1/Controllers/SobeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hotel_mvc1.Models;

namespace Hotel_mvc1.Controllers
{
    public class SobeController : Controller
    {
        private hotelBazaContext db = new hotelBazaContext();

        // GET: Sobe
        public ActionResult Index()
        {
            Session["MaxIDSoba"] = db.soba.Count();
            return View(db.soba.ToList());
        }

        // GET: Sobe/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.soba.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }
            return View(soba);
        }

        // GET: Sobe/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sobe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idsoba,brojSobe,brojKreveta,cijenaSobe")] Soba soba)
        {
            int id= Convert.ToInt32(soba.brojSobe);
            soba.idsoba = id;
            if (ModelState.IsValid)
            {
                db.soba.Add(soba);
                db.SaveChanges();
                int broj = Convert.ToInt32(Session["MaxIDSoba"]) + 1;
                Session["MaxIDSoba"]= broj;
                return RedirectToAction("Index");
            }

            return View(soba);
        }

        // GET: Sobe/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.soba.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }
            return View(soba);
        }

        // POST: Sobe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idsoba,brojSobe,brojKreveta,cijenaSobe")] Soba soba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(soba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(soba);
        }

        // GET: Sobe/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soba soba = db.soba.Find(id);
            if (soba == null)
            {
                return HttpNotFound();
            }
            return View(soba);
        }

        // POST: Sobe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Soba soba = db.soba.Find(id);
            db.soba.Remove(soba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hotel_mvc1/Views/Rezervacije/Create.cshtml
@model Hotel_mvc1.Models.Rezervacija



@{
    ViewBag.Title = "Create";
}
@*@{string session = (string)Session["id"];
   
   model.id_korisnik = int.Parse(session);
    @Html.EditorFor(model => model.id_korisnik )
}*@
@{   string rezOd = (string)Session["rezOd"];
    string rezDo = (string)Session["rezDo"];
    // int brSobe = Convert.ToInt32(TempData["prosjeđeniID"]);
    int max= Convert.ToInt32(Session["MaxIDSoba"]);
    //int brSobe2 = Model.id_soba;
    //List<Soba> sobe = new List<Soba>();
    //int identrifikator= Hotel_mvc1.Models.Soba
    int idSobe = 1;
    if (Session["sobaID"] != null)
    {
         idSobe = Convert.ToInt32(Session["sobaID"]);
    }

}
<h2>Nova rezervacija</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Rezervacija</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
         
        </div>
        <div class="form-group">
            
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.id_soba, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.id_soba, new { htmlAttributes = new { @class = "form-control", @min = "1",@max=max, Value=idSobe } })
                    @Html.ValidationMessageFor(model => model.id_soba, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.cijena, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.cijena, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.cijena, "", new { @class = "text-danger" })
                </div>
            </div>*@

            @*<div class="form-group">
                @Html.LabelFor(model => model.datumRezervacije, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.datumRezervacije, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.datumRezervacije, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.rezerviranoOd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.rezerviranoOd,rezOd, new { htmlAttributes = new { @class = "form-control", Value = rezOd } })
                    @Html.ValidationMessageFor(model => model.rezerviranoOd, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.rezerviranoDo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.rezerviranoDo,rezDo, new { htmlAttributes = new { @class = "form-control", Value = rezDo } })
                    @Html.ValidationMessageFor(model => model.rezerviranoDo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div id="obavijest" style="display: none; padding: 2px;"></div>
                    <input type="submit" value="Napravi rezervaciju" class="btn btn-default" />
                </div>
            </div>
        </div>
}
@{TempData["prosjeđeniID"] = null;
    }
<div>
    @Html.ActionLink("Natrag na listu", "Index")
</div>

Hotel_mvc1/Views/Rezervacije/Delete.cshtml
@model Hotel_mvc1.Models.Rezervacija

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Jeste li sigurni da želite obrisati rezervaciju?</h3>
<div>
    <h4>Rezervacija</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.id_korisnik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_korisnik)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.id_soba)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_soba)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datumRezervacije)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumRezervacije)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rezerviranoOd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rezerviranoOd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rezerviranoDo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rezerviranoDo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Obriši" class="btn btn-default" /> |
            @Html.ActionLink("Natrag na rezervacije", "Index")
        </div>
    }
</div>

Hotel_mvc1/Views/Rezervacije/Details.cshtml
@model Hotel_mvc1.Models.Rezervacija

@{
    ViewBag.Title = "Details";
}

<h2>Detalji</h2>

<div>
    <h4>Rezervacija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id_korisnik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_korisnik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.id_soba)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id_soba)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cijena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cijena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datumRezervacije)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumRezervacije)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rezerviranoOd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rezerviranoOd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rezerviranoDo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rezerviranoDo)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.idrezervacija }) |*@
    @Html.ActionLink("Natrag na rezervacije", "Index")
</p>

Hotel_mvc1/Views/Rezervacije/Edit.cshtml
@model Hotel_mvc1.Models.Rezervacija

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Rezervacija</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idrezervacija)

        <div class="form-group">
            @Html.LabelFor(model => model.id_korisnik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_korisnik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_korisnik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_soba, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_soba, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_soba, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cijena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cijena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datumRezervacije, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datumRezervacije, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datumRezervacije, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rezerviranoOd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rezerviranoOd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rezerviranoOd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rezerviranoDo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rezerviranoDo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rezerviranoDo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hotel_mvc1/Views/Rezervacije/Index.cshtml
@model IEnumerable<Hotel_mvc1.Models.Rezervacija>

@{
    ViewBag.Title = "Rezervacije";
}

<h2>Rezervacije</h2>
@{string session = (string)Session["uloga"];
    int id = Convert.ToInt32(Session["id"]);
}
@if(Session["idkorisnik"] != null)
{
<p>
    @Html.ActionLink("Nova rezervacija", "Create")

    @Html.ActionLink("Pretraga slobodnih smjestaja","Slobodni")
</p>
}

<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.id_korisnik)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.id_soba)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cijena)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datumRezervacije)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rezerviranoOd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.rezerviranoDo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    if (id == item.id_korisnik)
    {
            string dRez =  item.datumRezervacije.ToShortDateString();
            string rezOd = item.rezerviranoOd.ToShortDateString();
            string rezDo = item.rezerviranoDo.ToShortDateString();
                
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.id_korisnik)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.id_soba)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cijena)
        </td>
        <td>
            @Html.DisplayFor(modelItem => dRez)
        </td>
        <td>
            @Html.DisplayFor(modelItem => rezOd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => rezDo)
        </td>
     @if (Session["idkorisnik"] != null)
     {
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id = item.idrezervacija }) 
            </td>*@
            <td>
            @Html.ActionLink("Detalji", "Details", new { id = item.idrezervacija }) 
                </td>
                <td>
                        @Html.ActionLink("Obriši rezervaciju", "Delete", new { id = item.idrezervacija })
                </td>

     }
    </tr>
        }
    }

</table>

Hotel_mvc1/Views/Rezervacije/SlobodneSobe.cshtml
@model IEnumerable<Hotel_mvc1.Models.Soba>


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@{string session = (string)Session["uloga"];
    
}
@if (session == "admin")
{
    <p>
        @Html.ActionLink("Nova soba", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.brojSobe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.brojKreveta)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.brojSobe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brojKreveta)
            </td>
            <td>
                @Html.ActionLink("Detalji", "Details", "Sobe", new { id = item.idsoba },null)
            </td>
            <td>
                @*@{var prosljedeniID = item.idsoba;
                    TempData["prosjeđeniID"] = prosljedeniID;  }*@
                @Html.ActionLink("Rezerviraj", "Create", new { id = item.idsoba})
                
            </td>

            @*@if (session == "admin")
            {
                <td>
                    @Html.ActionLink(" Uredi", "Edit", new { id = item.idsoba })
                </td>
            }

            @if (session == "admin")
            {
                <td>
                    @Html.ActionLink(" Obrisi", "Delete", new { id = item.idsoba })

                </td>
            }*@

        </tr>
    }
</table>

Hotel_mvc1/Views/Rezervacije/Slobodni.cshtml
@model Hotel_mvc1.Models.Rezervacija
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{string session = (string)Session["uloga"];
    int id = Convert.ToInt32(Session["id"]);
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pretraga slobodnih smjestaja</title>
</head>
<h2>Pretraga slobodnih smjestaja</h2>
@using (Html.BeginForm())
{

<div class="form-group">
    @Html.LabelFor(model => model.rezerviranoOd, htmlAttributes: new { @class = "control-label col-md-1.2" })
    <div class="col-md-20">
        @Html.EditorFor(model => model.rezerviranoOd, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.rezerviranoOd, "", new { @class = "text-danger" })
    </div>
</div>


<div class="form-group">
    @Html.LabelFor(model => model.rezerviranoDo, htmlAttributes: new { @class = "control-label col-md-1.2" })
    <div class="col-md-20">
        @Html.EditorFor(model => model.rezerviranoDo, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.rezerviranoDo, "", new { @class = "text-danger" })
    </div>
</div>
<span></span>
<div>
    <input type="submit" value="Provjeri slobodne sobe" class="btn btn-default" />
</div>
}
<body>
    <div>

    </div>
</body>